server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_service?createDatabaseIfNotExist=true
    username: root
    password: Admin@root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
