server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_service?createDatabaseIfNotExist=true
    username: root
    password: Admin@root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE
